import { FamilyNode } from "./family-node.model";

export const mockNodes: FamilyNode[] = [
  {
    id: "0",
    name: "Павел Матора",
    description: "1850 c. Горбунки",
    firstParentId: undefined,
    secondParentId: undefined,
    childrenIds: ["1", "61", "62", "63", "82"],
  },
  {
    id: "1",
    name: "Илья",
    description: undefined,
    options: {
      expandable: true,
    },
    firstParentId: "0",
    secondParentId: undefined,
    childrenIds: ["2", "3", "4", "5", "6", "7"],
  },
  {
    id: "2",
    name: "Мария",
    description: undefined,
    firstParentId: "1",
    secondParentId: undefined,
    childrenIds: [],
  },
  {
    id: "3",
    name: "Фрося",
    description: undefined,
    firstParentId: "1",
    secondParentId: undefined,
    childrenIds: [],
  },
  {
    id: "4",
    name: "Анна",
    description: undefined,
    firstParentId: "1",
    secondParentId: undefined,
    childrenIds: [],
  },
  {
    id: "5",
    name: "Василий",
    description: undefined,
    firstParentId: "1",
    secondParentId: undefined,
    childrenIds: [],
  },
  {
    id: "6",
    name: "Иван",
    description: undefined,
    firstParentId: "1",
    secondParentId: undefined,
    childrenIds: [],
  },
  {
    id: "7",
    name: "Грегорий",
    description: "1876-1918",
    firstParentId: "1",
    secondParentId: undefined,
    childrenIds: ["8", "28", "29", "30", "31", "40", "41", "42", "46"],
  },
  {
    id: "90",
    name: "Анна Ильинична Салазко",
    description: "1880-1918",
    firstParentId: null,
    secondParentId: null,
    childrenIds: ["8", "28", "29", "30", "31", "40", "41", "42", "46"],
  },
  {
    id: "8",
    name: "Наталья",
    description: undefined,
    firstParentId: "7",
    secondParentId: "90",
    childrenIds: ["9", "14", "16", "17", "18", "19", "20", "27"],
  },
  {
    id: "91",
    name: "Александр Чичаевы",
    description: "1899-1981",
    firstParentId: null,
    secondParentId: null,
    childrenIds: ["9", "14", "16", "17", "18", "19", "20", "27"],
  },
  {
    id: "9",
    name: "Зинаида",
    description: "1922-2001 Самара",
    firstParentId: "8",
    secondParentId: "91",
    childrenIds: ["10"],
  },
  {
    id: "92",
    name: "Михаил Борисовы",
    description: undefined,
    firstParentId: null,
    secondParentId: null,
    childrenIds: ["10"],
  },
  {
    id: "10",
    name: "Татьяна",
    description: "1955",
    firstParentId: "9",
    secondParentId: "92",
    childrenIds: ["11", "12", "13"],
  },
  {
    id: "93",
    name: "Александр Остроуховы",
    description: undefined,
    firstParentId: null,
    secondParentId: null,
    childrenIds: ["11", "12", "13"],
  },
  {
    id: "11",
    name: "Александра",
    description: "1980",
    firstParentId: "10",
    secondParentId: "93",
    childrenIds: [],
  },
  {
    id: "12",
    name: "Наталья",
    description: "1983",
    firstParentId: "10",
    secondParentId: "93",
    childrenIds: [],
  },
  {
    id: "13",
    name: "Мария",
    description: "1997",
    firstParentId: "10",
    secondParentId: "93",
    childrenIds: [],
  },
  {
    id: "14",
    name: "Александра",
    description: "1923-2001 Самара",
    firstParentId: "8",
    secondParentId: "91",
    childrenIds: ["15"],
  },
  {
    id: "94",
    name: "Николай Федоровы",
    description: undefined,
    firstParentId: null,
    secondParentId: null,
    childrenIds: ["15"],
  },
  {
    id: "15",
    name: "Андрей",
    description: "1961 Самара",
    firstParentId: "14",
    secondParentId: "94",
    childrenIds: [],
  },
  {
    id: "16",
    name: "Галина",
    description: undefined,
    firstParentId: "8",
    secondParentId: "91",
    childrenIds: [],
  },
  {
    id: "17",
    name: "Геннадий",
    description: undefined,
    firstParentId: "8",
    secondParentId: "91",
    childrenIds: [],
  },
  {
    id: "18",
    name: "Вячеслав",
    description: undefined,
    firstParentId: "8",
    secondParentId: "91",
    childrenIds: [],
  },
  {
    id: "19",
    name: "Александр",
    description: undefined,
    firstParentId: "8",
    secondParentId: "91",
    childrenIds: [],
  },
  {
    id: "20",
    name: "Октябрина",
    description: "1938 Самара",
    firstParentId: "8",
    secondParentId: "91",
    childrenIds: ["21", "24"],
  },
  {
    id: "95",
    name: "Александр Гордеевы",
    description: undefined,
    firstParentId: null,
    secondParentId: null,
    childrenIds: ["21", "24"],
  },
  {
    id: "21",
    name: "Евгения",
    description: "1948",
    firstParentId: "20",
    secondParentId: "95",
    childrenIds: ["22", "23"],
  },
  {
    id: "96",
    name: "Владимир Клементьевы",
    description: undefined,
    firstParentId: null,
    secondParentId: null,
    childrenIds: ["22", "23"],
  },
  {
    id: "22",
    name: "Мари",
    description: "1992",
    firstParentId: "21",
    secondParentId: "96",
    childrenIds: [],
  },
  {
    id: "23",
    name: "Анастасия",
    description: "1992",
    firstParentId: "21",
    secondParentId: "96",
    childrenIds: [],
  },
  {
    id: "24",
    name: "Галина",
    description: "1969",
    firstParentId: "20",
    secondParentId: "95",
    childrenIds: ["25", "26"],
  },
  {
    id: "97",
    name: "Дмитрий Головы",
    description: undefined,
    firstParentId: null,
    secondParentId: null,
    childrenIds: ["25", "26"],
  },
  {
    id: "25",
    name: "Дарья",
    description: "1998",
    firstParentId: "24",
    secondParentId: "97",
    childrenIds: [],
  },
  {
    id: "26",
    name: "Василий",
    description: "2011",
    firstParentId: "24",
    secondParentId: "97",
    childrenIds: [],
  },
  {
    id: "27",
    name: "Лидия",
    description: undefined,
    firstParentId: "8",
    secondParentId: "91",
    childrenIds: [],
  },
  {
    id: "28",
    name: "Дмитрий",
    description: "1901-1943",
    firstParentId: "7",
    secondParentId: "90",
    childrenIds: [],
  },
  {
    id: "29",
    name: "Ефросинья",
    description: undefined,
    firstParentId: "7",
    secondParentId: "90",
    childrenIds: [],
  },
  {
    id: "98",
    name: "Василий Яковлевы",
    description: "1903-1981",
    firstParentId: null,
    secondParentId: null,
    childrenIds: [],
  },
  {
    id: "30",
    name: "Александр",
    description: undefined,
    firstParentId: "7",
    secondParentId: "90",
    childrenIds: [],
  },
  {
    id: "99",
    name: "Софья Моторовы",
    description: "1904-1979",
    firstParentId: null,
    secondParentId: null,
    childrenIds: [],
  },
  {
    id: "31",
    name: "Пелагея",
    description: undefined,
    firstParentId: "7",
    secondParentId: "90",
    childrenIds: ["32"],
  },
  {
    id: "100",
    name: "Ануфрий Рогоза",
    description: undefined,
    firstParentId: null,
    secondParentId: null,
    childrenIds: ["32"],
  },
  {
    id: "32",
    name: "Валентина",
    description: undefined,
    firstParentId: "31",
    secondParentId: "100",
    childrenIds: ["33", "34", "35"],
  },
  {
    id: "101",
    name: "Сергей Прилягины",
    description: "1946",
    firstParentId: null,
    secondParentId: null,
    childrenIds: ["33", "34", "35"],
  },
  {
    id: "33",
    name: "Екатерина",
    description: undefined,
    firstParentId: "32",
    secondParentId: "101",
    childrenIds: [],
  },
  {
    id: "34",
    name: "Елена",
    description: undefined,
    firstParentId: "32",
    secondParentId: "101",
    childrenIds: [],
  },
  {
    id: "35",
    name: "Александр",
    description: "1944",
    firstParentId: "32",
    secondParentId: "101",
    childrenIds: ["36", "39"],
  },
  {
    id: "102",
    name: "Светлана Прилягины",
    description: "1945",
    firstParentId: null,
    secondParentId: null,
    childrenIds: ["36", "39"],
  },
  {
    id: "36",
    name: "Павел",
    description: "1969-1996",
    firstParentId: "35",
    secondParentId: "102",
    childrenIds: ["37", "38"],
  },
  {
    id: "37",
    name: "Дария",
    description: "1992",
    firstParentId: "36",
    secondParentId: undefined,
    childrenIds: [],
  },
  {
    id: "38",
    name: "Анна",
    description: "1995",
    firstParentId: "36",
    secondParentId: undefined,
    childrenIds: [],
  },
  {
    id: "39",
    name: "Анастасия",
    description: "1974-1996",
    firstParentId: "35",
    secondParentId: "102",
    childrenIds: [],
  },
  {
    id: "40",
    name: "Екатерина",
    description: "1909-1945",
    firstParentId: "7",
    secondParentId: "90",
    childrenIds: [],
  },
  {
    id: "41",
    name: "Елена",
    description: undefined,
    firstParentId: "7",
    secondParentId: "90",
    childrenIds: [],
  },
  {
    id: "103",
    name: "Иван Андрасюк",
    description: "1912-1984",
    firstParentId: null,
    secondParentId: null,
    childrenIds: [],
  },
  {
    id: "42",
    name: "Евгения",
    description: undefined,
    firstParentId: "7",
    secondParentId: "90",
    childrenIds: ["43"],
  },
  {
    id: "104",
    name: "Леонид Матора",
    description: "1912-1984",
    firstParentId: null,
    secondParentId: null,
    childrenIds: ["43"],
  },
  {
    id: "43",
    name: "Ирина",
    description: undefined,
    firstParentId: "42",
    secondParentId: "104",
    childrenIds: ["44"],
  },
  {
    id: "105",
    name: "Анатолий Рогаза",
    description: "1946-",
    firstParentId: null,
    secondParentId: null,
    childrenIds: ["44"],
  },
  {
    id: "44",
    name: "Елена",
    description: undefined,
    firstParentId: "43",
    secondParentId: "105",
    childrenIds: ["45"],
  },
  {
    id: "106",
    name: "Дмитрий",
    description: "1972",
    firstParentId: null,
    secondParentId: null,
    childrenIds: ["45"],
  },
  {
    id: "45",
    name: "Александр",
    description: "1996-2005",
    firstParentId: "44",
    secondParentId: "106",
    childrenIds: [],
  },
  {
    id: "46",
    name: "Никифор",
    description: "1917-1998",
    firstParentId: "7",
    secondParentId: "90",
    childrenIds: ["47", "50", "51"],
  },
  {
    id: "107",
    name: "Нина Матора",
    description: "1918-2004",
    firstParentId: null,
    secondParentId: null,
    childrenIds: ["47", "50", "51"],
  },
  {
    id: "47",
    name: "Владимир",
    description: undefined,
    firstParentId: "46",
    secondParentId: "107",
    childrenIds: ["48"],
  },
  {
    id: "108",
    name: "Нина Матора",
    description: "1939-2000",
    firstParentId: null,
    secondParentId: null,
    childrenIds: ["48"],
  },
  {
    id: "48",
    name: "Екатерина",
    description: "1972",
    firstParentId: "47",
    secondParentId: "108",
    childrenIds: ["49"],
  },
  {
    id: "49",
    name: "Алеша",
    description: "2006",
    firstParentId: "48",
    secondParentId: undefined,
    childrenIds: [],
  },
  {
    id: "50",
    name: "Майя",
    description: "1941-1944",
    firstParentId: "46",
    secondParentId: "107",
    childrenIds: [],
  },
  {
    id: "51",
    name: "Анатолий",
    description: undefined,
    firstParentId: "46",
    secondParentId: "107",
    childrenIds: ["52", "55", "58"],
  },
  {
    id: "109",
    name: "Галина Мотора",
    description: "1946",
    firstParentId: null,
    secondParentId: null,
    childrenIds: ["52", "55", "58"],
  },
  {
    id: "52",
    name: "Георгий",
    description: "1969",
    firstParentId: "51",
    secondParentId: "109",
    childrenIds: ["53", "54"],
  },
  {
    id: "110",
    name: "Елена Мотора",
    description: "1971",
    firstParentId: null,
    secondParentId: null,
    childrenIds: ["53", "54"],
  },
  {
    id: "53",
    name: "Рита",
    description: "1997",
    firstParentId: "52",
    secondParentId: "110",
    childrenIds: [],
  },
  {
    id: "54",
    name: "Анастасия",
    description: "2006",
    firstParentId: "52",
    secondParentId: "110",
    childrenIds: [],
  },
  {
    id: "55",
    name: "Татьяна",
    description: "1972",
    firstParentId: "51",
    secondParentId: "109",
    childrenIds: ["56", "57"],
  },
  {
    id: "56",
    name: "Дарья",
    description: "1999",
    firstParentId: "55",
    secondParentId: undefined,
    childrenIds: [],
  },
  {
    id: "57",
    name: "Иван",
    description: "2006",
    firstParentId: "55",
    secondParentId: undefined,
    childrenIds: [],
  },
  {
    id: "58",
    name: "Нина",
    description: "1979",
    firstParentId: "51",
    secondParentId: "109",
    childrenIds: ["59", "60"],
  },
  {
    id: "111",
    name: "Максим Богомаз",
    description: "1976",
    firstParentId: null,
    secondParentId: null,
    childrenIds: ["59", "60"],
  },
  {
    id: "59",
    name: "Екатерина",
    description: "2010",
    firstParentId: "58",
    secondParentId: "111",
    childrenIds: [],
  },
  {
    id: "60",
    name: "Вера",
    description: "2014",
    firstParentId: "58",
    secondParentId: "111",
    childrenIds: [],
  },
  {
    id: "61",
    name: "Григорий",
    description: undefined,
    firstParentId: "0",
    secondParentId: undefined,
    childrenIds: [],
  },
  {
    id: "62",
    name: "Егор",
    description: undefined,
    firstParentId: "0",
    secondParentId: undefined,
    childrenIds: [],
  },
  {
    id: "63",
    name: "Борис",
    description: undefined,
    options: {
      expandable: true,
    },
    firstParentId: "0",
    secondParentId: undefined,
    childrenIds: ["64", "67", "74"],
  },
  {
    id: "64",
    name: "Пелагея",
    description: undefined,
    firstParentId: "63",
    secondParentId: undefined,
    childrenIds: ["65"],
  },
  {
    id: "65",
    name: "Таисия Сакки",
    description: undefined,
    firstParentId: "64",
    secondParentId: undefined,
    childrenIds: ["66"],
  },
  {
    id: "66",
    name: "Татьяна",
    description: "Севастополь",
    firstParentId: "65",
    secondParentId: undefined,
    childrenIds: [],
  },
  {
    id: "67",
    name: "Марина",
    description: undefined,
    firstParentId: "63",
    secondParentId: undefined,
    childrenIds: ["68", "70", "72"],
  },
  {
    id: "68",
    name: "Раиса",
    description: undefined,
    firstParentId: "67",
    secondParentId: undefined,
    childrenIds: ["69"],
  },
  {
    id: "69",
    name: "Сын",
    description: undefined,
    firstParentId: "68",
    secondParentId: undefined,
    childrenIds: [],
  },
  {
    id: "70",
    name: "Зинаида",
    description: undefined,
    firstParentId: "67",
    secondParentId: undefined,
    childrenIds: ["71"],
  },
  {
    id: "71",
    name: "5 детей",
    description: undefined,
    firstParentId: "70",
    secondParentId: undefined,
    childrenIds: [],
  },
  {
    id: "72",
    name: "Виктор",
    description: undefined,
    firstParentId: "67",
    secondParentId: undefined,
    childrenIds: ["73"],
  },
  {
    id: "73",
    name: "2 ребенка",
    description: undefined,
    firstParentId: "72",
    secondParentId: undefined,
    childrenIds: [],
  },
  {
    id: "74",
    name: "Марфа",
    description: "1952",
    firstParentId: "63",
    secondParentId: undefined,
    childrenIds: ["75", "76", "77", "78", "79", "80", "81"],
  },
  {
    id: "112",
    name: "Дмитрий Салазко",
    description: "1947",
    firstParentId: null,
    secondParentId: null,
    childrenIds: ["75", "76", "77", "78", "79", "80", "81"],
  },
  {
    id: "75",
    name: "Иван",
    description: undefined,
    firstParentId: "74",
    secondParentId: "112",
    childrenIds: [],
  },
  {
    id: "76",
    name: "Нина",
    description: undefined,
    firstParentId: "74",
    secondParentId: "112",
    childrenIds: [],
  },
  {
    id: "113",
    name: "Нинакор Вязянко",
    description: undefined,
    firstParentId: null,
    secondParentId: null,
    childrenIds: [],
  },
  {
    id: "77",
    name: "Виктория",
    description: undefined,
    firstParentId: "74",
    secondParentId: "112",
    childrenIds: [],
  },
  {
    id: "78",
    name: "Петр",
    description: undefined,
    firstParentId: "74",
    secondParentId: "112",
    childrenIds: [],
  },
  {
    id: "79",
    name: "Лидия",
    description: undefined,
    firstParentId: "74",
    secondParentId: "112",
    childrenIds: [],
  },
  {
    id: "80",
    name: "Валентина",
    description: undefined,
    firstParentId: "74",
    secondParentId: "112",
    childrenIds: [],
  },
  {
    id: "81",
    name: "Ольга",
    description: undefined,
    firstParentId: "74",
    secondParentId: "112",
    childrenIds: [],
  },
  {
    id: "82",
    name: "Петр",
    description: undefined,
    firstParentId: "0",
    options: {
      expandable: true,
    },
    secondParentId: undefined,
    childrenIds: ["83"],
  },
  {
    id: "83",
    name: "Евдокия",
    description: undefined,
    firstParentId: "82",
    secondParentId: undefined,
    childrenIds: ["84", "85", "86"],
  },
  {
    id: "114",
    name: "Александр Прохоренко",
    description: "Ушково",
    firstParentId: null,
    secondParentId: null,
    childrenIds: ["84", "85", "86"],
  },
  {
    id: "84",
    name: "Вадим",
    description: undefined,
    firstParentId: "83",
    secondParentId: "114",
    childrenIds: [],
  },
  {
    id: "115",
    name: "Людмила",
    description: undefined,
    firstParentId: null,
    secondParentId: null,
    childrenIds: [],
  },
  {
    id: "85",
    name: "Нина",
    description: undefined,
    firstParentId: "83",
    secondParentId: "114",
    childrenIds: [],
  },
  {
    id: "86",
    name: "Валентина",
    description: undefined,
    firstParentId: "83",
    secondParentId: "114",
    childrenIds: ["87", "88"],
  },
  {
    id: "87",
    name: "Юра",
    description: undefined,
    firstParentId: "86",
    secondParentId: undefined,
    childrenIds: [],
  },
  {
    id: "88",
    name: "Зоя",
    description: undefined,
    firstParentId: "86",
    secondParentId: undefined,
    childrenIds: [],
  },
];
