/**
 * Family Tree Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface UserOutputDtoModel {
  email: string;
  firstname: string | null;
  lastname: string | null;
  role: UserOutputDtoModel.RoleEnum;
  createdAt: string;
  updatedAt: string;
  id: string;
  password: string;
}

export namespace UserOutputDtoModel {
  export type RoleEnum = 'ADMIN' | 'USER';
  export const RoleEnum = {
    Admin: 'ADMIN' as RoleEnum,
    User: 'USER' as RoleEnum,
  };
}
